test('test1',() => console.log('test 1'))
test('test2',() => console.log('test 3'))
test('test3',() => console.log('test 2'))
test.skip('test4',() => console.log('test 4'))
test('test5',() => console.log('test 5'))